Fix docker login

diff --git a/.github/workflows/build-docker.yml b/.github/workflows/build-docker.yml
--- a/.github/workflows/build-docker.yml
+++ b/.github/workflows/build-docker.yml
@@ -32,13 +32,13 @@ jobs:
       - name: Set up Docker Buildx
         uses: docker/setup-buildx-action@v3
 
-      # Log in to the container registry
-      - name: Log in to registry
-        uses: docker/login-action@v3
-        with:
-          registry: registry.abstrax.cn
-          username: ${{ secrets.REGISTRY_USERNAME }}
-          password: ${{ secrets.REGISTRY_PASSWORD }}
+      # # Log in to the container registry
+      # - name: Log in to registry
+      #   uses: docker/login-action@v3
+      #   with:
+      #     registry: registry.abstrax.cn
+      #     username: ${{ secrets.REGISTRY_USERNAME }}
+      #     password: ${{ secrets.REGISTRY_PASSWORD }}
 
       # Extract unique problem folders from changed files
       - name: Extract problem folders
@@ -68,6 +68,15 @@ jobs:
           REGISTRY: registry.abstrax.cn
         run: |
           images=()
+
+          echo "Login to registry" >&2
+          echo "${{ secrets.REGISTRY_PASSWORD }}" | docker login $REGISTRY -u "${{ secrets.REGISTRY_USERNAME }}" --password-stdin
+          if [ $? -ne 0 ]; then
+            echo "Docker login failed" >&2
+            exit 1
+          else
+            echo "Docker login succeeded" >&2
+          fi
 
           # Loop through changed problem folders
           problem_folders="${{ steps.changed-folders.outputs.problem_folders }}"
